import FortfolioImg from "../../../assets/projectimg/fortfolio.png";

export const projects = [
  {
    title: "Riot Games 게임사의 전적검색 사이트",
    date: "2024.9 ~ Present",
    projecttype: "Team",
    description:
      "Riot Games 게임사에서 서비스 중인 게임의 전적검색 및 정보 제공 사이트",
    image1: "/images/.png",
    image2: "/images/.png",
    skills: [
      "React",
      "JavaScript",
      "Node.js",
      "PostgreSQL",
      "Jenkins",
      "Docker",
      "Gitlab",
      "Unix",
      "Raspberry-Pi",
    ],
  },
  {
    title: "개인 Portfolio & Blog 페이지 제작",
    date: "2025.04 ~ Present",
    projecttype: "Personal",
    description: "React + Tailwind로 만든 반응형 개인 포트폴리오 페이지",
    image1: FortfolioImg,
    image2: "/images/.png",
    skills: [
      "React",
      "Next.js",
      "TypeScript",
      "TailwindCSS",
      "Zustand",
      "Vercel",
      "Github",
    ],
  },
  {
    title: "ChatGPT API를 활용한 프로젝트 1",
    date: "진행날짜 부분",
    projecttype: "Team",
    description: "Project4 프로젝트 설명 부분",
    image1: "/images/.png",
    image2: "/images/.png",
    skills: ["Next.js"],
  },
  {
    title: "구름 부트캠프에서 진행되는 프로젝트 1",
    date: "진행날짜 부분",
    projecttype: "Team",
    description: "Project 프로젝트 설명 부분",
    image1: "/images/.png",
    image2: "/images/.png",
    skills: ["React"],
  },
  {
    title: "구름 부트캠프에서 진행되는 프로젝트 2",
    date: "진행날짜 부분",
    projecttype: "Team",
    description: "Project 프로젝트 설명 부분",
    image1: "/images/.png",
    image2: "/images/.png",
    skills: ["React"],
  },
];
